import type { PaymentRail, RailFieldDef } from './types';

// ─── Reusable field definitions ────────────────────────────────

const cardFields: RailFieldDef[] = [
  { id: 'pan', label: 'Card Number', placeholder: '4242 4242 4242 4242', format: 'card_number', position: 'front', required: true, maxLength: 19 },
  { id: 'expiry', label: 'Expiry Date', placeholder: '12/28', format: 'freeform', position: 'front', required: true, maxLength: 5 },
  { id: 'cvv', label: 'CVV', placeholder: '***', format: 'freeform', position: 'back', required: false, maxLength: 3 },
  { id: 'cardholder', label: 'Cardholder Name', placeholder: 'JANE A. CARDHOLDER', format: 'freeform', position: 'front', required: true, maxLength: 26 },
];

const amexFields: RailFieldDef[] = [
  { id: 'pan', label: 'Card Number', placeholder: '3782 822463 10005', format: 'card_number', position: 'front', required: true, maxLength: 17 },
  { id: 'expiry', label: 'Member Since', placeholder: '2024', format: 'freeform', position: 'front', required: true, maxLength: 4 },
  { id: 'cvv', label: 'CID', placeholder: '****', format: 'freeform', position: 'front', required: false, maxLength: 4 },
  { id: 'cardholder', label: 'Card Member', placeholder: 'JANE A. CARDHOLDER', format: 'freeform', position: 'front', required: true, maxLength: 26 },
];

const debitCardFields: RailFieldDef[] = [
  { id: 'pan', label: 'Card Number', placeholder: '4242 4242 4242 4242', format: 'card_number', position: 'front', required: true, maxLength: 19 },
  { id: 'expiry', label: 'Valid Thru', placeholder: '12/28', format: 'freeform', position: 'front', required: true, maxLength: 5 },
  { id: 'cardholder', label: 'Cardholder Name', placeholder: 'JANE A. CARDHOLDER', format: 'freeform', position: 'front', required: true, maxLength: 26 },
];

const wireFields: RailFieldDef[] = [
  { id: 'bic', label: 'BIC / SWIFT Code', placeholder: 'CHASUS33XXX', format: 'swift_bic', position: 'front', required: true, maxLength: 11 },
  { id: 'iban', label: 'IBAN / Account', placeholder: 'US12 3456 7890 1234 5678', format: 'iban', position: 'front', required: true, maxLength: 34 },
  { id: 'beneficiary', label: 'Beneficiary', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'reference', label: 'Reference', placeholder: 'INV-2024-001', format: 'freeform', position: 'front', required: false, maxLength: 35 },
  { id: 'bank', label: 'Bank Name', placeholder: 'JPMorgan Chase', format: 'freeform', position: 'front', required: false, maxLength: 35 },
];

const achFields: RailFieldDef[] = [
  { id: 'routing', label: 'Routing Number', placeholder: '021000021', format: 'routing_number', position: 'front', required: true, maxLength: 9 },
  { id: 'account', label: 'Account Number', placeholder: '123456789012', format: 'freeform', position: 'front', required: true, maxLength: 17 },
  { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'bank', label: 'Bank Name', placeholder: 'Wells Fargo', format: 'freeform', position: 'front', required: false, maxLength: 35 },
  { id: 'type', label: 'Account Type', placeholder: 'Checking', format: 'freeform', position: 'front', required: false, maxLength: 15 },
];

const sepaFields: RailFieldDef[] = [
  { id: 'iban', label: 'IBAN', placeholder: 'DE89 3704 0044 0532 0130 00', format: 'iban', position: 'front', required: true, maxLength: 34 },
  { id: 'bic', label: 'BIC', placeholder: 'COBADEFFXXX', format: 'swift_bic', position: 'front', required: false, maxLength: 11 },
  { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'reference', label: 'Reference', placeholder: 'RF18 5390 0754 7034', format: 'freeform', position: 'front', required: false, maxLength: 35 },
];

const ukBankFields: RailFieldDef[] = [
  { id: 'sortcode', label: 'Sort Code', placeholder: '20-00-00', format: 'sort_code', position: 'front', required: true, maxLength: 8 },
  { id: 'account', label: 'Account Number', placeholder: '12345678', format: 'freeform', position: 'front', required: true, maxLength: 8 },
  { id: 'holder', label: 'Payee Name', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'reference', label: 'Reference', placeholder: 'Payment ref', format: 'freeform', position: 'front', required: false, maxLength: 18 },
];

const rtpPhoneFields: RailFieldDef[] = [
  { id: 'phone', label: 'Phone Number', placeholder: '+1 234 567 8900', format: 'phone', position: 'front', required: true, maxLength: 15 },
  { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'bank', label: 'Bank / Provider', placeholder: 'Bank Name', format: 'freeform', position: 'front', required: false, maxLength: 35 },
];

const upiFields: RailFieldDef[] = [
  { id: 'upi_id', label: 'UPI ID (VPA)', placeholder: 'jane@upi', format: 'upi_id', position: 'front', required: true, maxLength: 50 },
  { id: 'phone', label: 'Mobile Number', placeholder: '+91 98765 43210', format: 'phone', position: 'front', required: false, maxLength: 13 },
  { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'bank', label: 'Bank Name', placeholder: 'State Bank of India', format: 'freeform', position: 'front', required: false, maxLength: 35 },
];

const pixFields: RailFieldDef[] = [
  { id: 'pix_key', label: 'PIX Key', placeholder: 'CPF, email, phone, or random', format: 'freeform', position: 'front', required: true, maxLength: 77 },
  { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'bank', label: 'Bank / PSP', placeholder: 'Nubank', format: 'freeform', position: 'front', required: false, maxLength: 35 },
];

const mobileMoneyFields: RailFieldDef[] = [
  { id: 'phone', label: 'Mobile Number', placeholder: '+254 712 345678', format: 'phone', position: 'front', required: true, maxLength: 15 },
  { id: 'holder', label: 'Account Name', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'agent', label: 'Agent / Till Number', placeholder: '123456', format: 'freeform', position: 'front', required: false, maxLength: 10 },
];

const bnplFields: RailFieldDef[] = [
  { id: 'pan', label: 'Virtual Card Number', placeholder: '4242 4242 4242 4242', format: 'card_number', position: 'front', required: false, maxLength: 19 },
  { id: 'holder', label: 'Customer Name', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'plan', label: 'Installment Plan', placeholder: 'Pay in 4', format: 'freeform', position: 'front', required: false, maxLength: 25 },
];

const cryptoFields: RailFieldDef[] = [
  { id: 'address', label: 'Wallet Address', placeholder: '0x742d35Cc6634C0532...', format: 'wallet_address', position: 'front', required: true, maxLength: 64 },
  { id: 'chain', label: 'Network / Chain', placeholder: 'Ethereum Mainnet', format: 'freeform', position: 'front', required: false, maxLength: 25 },
  { id: 'holder', label: 'Display Name', placeholder: 'jane.eth', format: 'freeform', position: 'front', required: false, maxLength: 35 },
];

const openBankingFields: RailFieldDef[] = [
  { id: 'account_ref', label: 'Account Reference', placeholder: 'acct_abc123', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'provider', label: 'Provider / Bank', placeholder: 'Monzo', format: 'freeform', position: 'front', required: true, maxLength: 35 },
  { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
];

// ─── Payment Rails Registry ───────────────────────────────────

export const paymentRails: PaymentRail[] = [

  // ═══════════════════════════════════════════════════════════
  // CARD NETWORKS
  // ═══════════════════════════════════════════════════════════

  {
    id: 'visa',
    name: 'Visa',
    category: 'card_network',
    region: 'global',
    logoFile: '/logos/visa.svg',
    logoFileLight: '/logos/visa-white.svg',
    popularity: 10,
    tiers: [
      { id: 'classic', label: 'CLASSIC', fullLabel: 'Visa Classic' },
      { id: 'gold', label: 'GOLD', fullLabel: 'Visa Gold' },
      { id: 'platinum', label: 'PLATINUM', fullLabel: 'Visa Platinum' },
      { id: 'signature', label: 'SIGNATURE', fullLabel: 'Visa Signature' },
      { id: 'infinite', label: 'INFINITE', fullLabel: 'Visa Infinite' },
      { id: 'business', label: 'BUSINESS', fullLabel: 'Visa Business' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'mastercard',
    name: 'Mastercard',
    category: 'card_network',
    region: 'global',
    logoFile: '/logos/mastercard.svg',
    popularity: 10,
    tiers: [
      { id: 'standard', label: 'STANDARD', fullLabel: 'Mastercard Standard' },
      { id: 'gold', label: 'GOLD', fullLabel: 'Mastercard Gold' },
      { id: 'platinum', label: 'PLATINUM', fullLabel: 'Mastercard Platinum' },
      { id: 'world', label: 'WORLD', fullLabel: 'Mastercard World' },
      { id: 'world_elite', label: 'WORLD ELITE', fullLabel: 'World Elite' },
      { id: 'business', label: 'BUSINESS', fullLabel: 'Mastercard Business' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'amex',
    name: 'American Express',
    shortName: 'Amex',
    category: 'card_network',
    region: 'global',
    logoFile: '/logos/amex.svg',
    popularity: 9,
    tiers: [
      { id: 'green', label: 'GREEN', fullLabel: 'Amex Green' },
      { id: 'gold', label: 'GOLD', fullLabel: 'Amex Gold' },
      { id: 'platinum', label: 'PLATINUM', fullLabel: 'Amex Platinum' },
      { id: 'centurion', label: 'CENTURION', fullLabel: 'Amex Centurion' },
      { id: 'corporate', label: 'CORPORATE', fullLabel: 'Amex Corporate' },
    ],
    fields: amexFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'MEMBER SINCE',
    cvvLength: 4,
  },
  {
    id: 'discover',
    name: 'Discover',
    category: 'card_network',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/discover.svg',
    popularity: 7,
    tiers: [
      { id: 'it', label: 'IT', fullLabel: 'Discover it' },
      { id: 'miles', label: 'MILES', fullLabel: 'Discover Miles' },
      { id: 'cashback', label: 'CASHBACK', fullLabel: 'Discover Cashback' },
      { id: 'business', label: 'BUSINESS', fullLabel: 'Discover Business' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'unionpay',
    name: 'UnionPay',
    category: 'card_network',
    region: 'asia_pacific',
    country: 'CN',
    logoFile: '/logos/unionpay.svg',
    popularity: 9,
    tiers: [
      { id: 'standard', label: 'STANDARD', fullLabel: 'UnionPay Standard' },
      { id: 'premium', label: 'PREMIUM', fullLabel: 'UnionPay Premium' },
      { id: 'diamond', label: 'DIAMOND', fullLabel: 'UnionPay Diamond' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'jcb',
    name: 'JCB',
    category: 'card_network',
    region: 'asia_pacific',
    country: 'JP',
    logoFile: '/logos/jcb.svg',
    popularity: 6,
    tiers: [
      { id: 'standard', label: 'STANDARD', fullLabel: 'JCB Standard' },
      { id: 'gold', label: 'GOLD', fullLabel: 'JCB Gold' },
      { id: 'the_class', label: 'THE CLASS', fullLabel: 'JCB The Class' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'diners',
    name: 'Diners Club',
    shortName: 'Diners',
    category: 'card_network',
    region: 'global',
    logoFile: '/logos/rails/card/diners.svg',
    popularity: 5,
    tiers: [
      { id: 'standard', label: 'STANDARD', fullLabel: 'Diners Club' },
      { id: 'premium', label: 'PREMIUM', fullLabel: 'Diners Club Premium' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'maestro',
    name: 'Maestro',
    category: 'card_network',
    region: 'europe',
    logoFile: '/logos/maestro.svg',
    popularity: 4,
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'cb',
    name: 'Cartes Bancaires',
    shortName: 'CB',
    category: 'card_network',
    region: 'europe',
    country: 'FR',
    logoFile: '/logos/rails/card/cb.svg',
    popularity: 6,
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'mir',
    name: 'Mir',
    category: 'card_network',
    region: 'europe',
    country: 'RU',
    logoFile: '/logos/rails/card/mir.svg',
    popularity: 5,
    tiers: [
      { id: 'standard', label: 'STANDARD', fullLabel: 'Mir Standard' },
      { id: 'premium', label: 'PREMIUM', fullLabel: 'Mir Premium' },
      { id: 'supreme', label: 'SUPREME', fullLabel: 'Mir Supreme' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'troy',
    name: 'Troy',
    category: 'card_network',
    region: 'middle_east',
    country: 'TR',
    logoFile: '/logos/rails/card/troy.svg',
    popularity: 4,
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'verve',
    name: 'Verve',
    category: 'card_network',
    region: 'africa',
    country: 'NG',
    logoFile: '/logos/rails/card/verve.svg',
    popularity: 5,
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'elo',
    name: 'Elo',
    category: 'card_network',
    region: 'latin_america',
    country: 'BR',
    logoFile: '/logos/rails/card/elo.svg',
    popularity: 6,
    tiers: [
      { id: 'standard', label: 'STANDARD', fullLabel: 'Elo Standard' },
      { id: 'mais', label: 'MAIS', fullLabel: 'Elo Mais' },
      { id: 'nanquim', label: 'NANQUIM', fullLabel: 'Elo Nanquim' },
    ],
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'hipercard',
    name: 'Hipercard',
    category: 'card_network',
    region: 'latin_america',
    country: 'BR',
    logoFile: '/logos/rails/card/hipercard.svg',
    popularity: 4,
    fields: cardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },

  // ═══════════════════════════════════════════════════════════
  // DOMESTIC DEBIT
  // ═══════════════════════════════════════════════════════════

  {
    id: 'interac',
    name: 'Interac',
    category: 'domestic_debit',
    region: 'north_america',
    country: 'CA',
    logoFile: '/logos/interac.svg',
    popularity: 9,
    tiers: [
      { id: 'debit', label: 'DEBIT', fullLabel: 'Interac Debit' },
      { id: 'flash', label: 'FLASH', fullLabel: 'Interac Flash' },
    ],
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'eftpos',
    name: 'eftpos',
    category: 'domestic_debit',
    region: 'asia_pacific',
    country: 'AU',
    logoFile: '/logos/rails/debit/eftpos.svg',
    popularity: 8,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'rupay',
    name: 'RuPay',
    category: 'domestic_debit',
    region: 'asia_pacific',
    country: 'IN',
    logoFile: '/logos/rails/debit/rupay.svg',
    popularity: 9,
    tiers: [
      { id: 'classic', label: 'CLASSIC', fullLabel: 'RuPay Classic' },
      { id: 'platinum', label: 'PLATINUM', fullLabel: 'RuPay Platinum' },
      { id: 'select', label: 'SELECT', fullLabel: 'RuPay Select' },
    ],
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'girocard',
    name: 'girocard',
    category: 'domestic_debit',
    region: 'europe',
    country: 'DE',
    logoFile: '/logos/rails/debit/girocard.svg',
    popularity: 8,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'bancontact',
    name: 'Bancontact',
    category: 'domestic_debit',
    region: 'europe',
    country: 'BE',
    logoFile: '/logos/rails/debit/bancontact.svg',
    popularity: 7,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'ideal',
    name: 'iDEAL',
    category: 'domestic_debit',
    region: 'europe',
    country: 'NL',
    logoFile: '/logos/rails/debit/ideal.svg',
    popularity: 7,
    fields: sepaFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#CC0066' },
  },
  {
    id: 'dankort',
    name: 'Dankort',
    category: 'domestic_debit',
    region: 'europe',
    country: 'DK',
    logoFile: '/logos/rails/debit/dankort.svg',
    popularity: 5,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'mada',
    name: 'mada',
    category: 'domestic_debit',
    region: 'middle_east',
    country: 'SA',
    logoFile: '/logos/rails/debit/mada.svg',
    popularity: 8,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'knet',
    name: 'KNET',
    category: 'domestic_debit',
    region: 'middle_east',
    country: 'KW',
    logoFile: '/logos/rails/debit/knet.svg',
    popularity: 6,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'bancnet',
    name: 'BancNet',
    category: 'domestic_debit',
    region: 'asia_pacific',
    country: 'PH',
    logoFile: '/logos/rails/debit/bancnet.svg',
    popularity: 5,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'napas',
    name: 'NAPAS',
    category: 'domestic_debit',
    region: 'asia_pacific',
    country: 'VN',
    logoFile: '/logos/rails/debit/napas.svg',
    popularity: 6,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },
  {
    id: 'bccard',
    name: 'BC Card',
    category: 'domestic_debit',
    region: 'asia_pacific',
    country: 'KR',
    logoFile: '/logos/rails/debit/bccard.svg',
    popularity: 6,
    fields: debitCardFields,
    hasChip: true,
    hasContactless: true,
    hasQrCode: false,
    cardFormFactor: 'standard_card',
    expiryLabel: 'VALID THRU',
    cvvLength: 3,
  },

  // ═══════════════════════════════════════════════════════════
  // REAL-TIME PAYMENTS
  // ═══════════════════════════════════════════════════════════

  {
    id: 'upi',
    name: 'Unified Payments Interface',
    shortName: 'UPI',
    category: 'realtime_payment',
    region: 'asia_pacific',
    country: 'IN',
    logoFile: '/logos/rails/rtp/upi.svg',
    popularity: 10,
    fields: upiFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#4CAF50', secondary: '#2E7D32' },
  },
  {
    id: 'pix',
    name: 'PIX',
    category: 'realtime_payment',
    region: 'latin_america',
    country: 'BR',
    logoFile: '/logos/rails/rtp/pix.svg',
    popularity: 10,
    fields: pixFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#32BCAD', secondary: '#00A8A0' },
  },
  {
    id: 'fednow',
    name: 'FedNow',
    category: 'realtime_payment',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/rtp/fednow.svg',
    popularity: 8,
    fields: achFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003A70' },
  },
  {
    id: 'fps',
    name: 'Faster Payments',
    shortName: 'FPS',
    category: 'realtime_payment',
    region: 'europe',
    country: 'GB',
    logoFile: '/logos/rails/rtp/fps.svg',
    popularity: 9,
    fields: ukBankFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#FF6600' },
  },
  {
    id: 'sepa_instant',
    name: 'SEPA Instant',
    shortName: 'SCT Inst',
    category: 'realtime_payment',
    region: 'europe',
    countries: ['EU'],
    logoFile: '/logos/rails/rtp/sepa-instant.svg',
    popularity: 8,
    fields: sepaFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003399' },
  },
  {
    id: 'zelle',
    name: 'Zelle',
    category: 'realtime_payment',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/rtp/zelle.svg',
    popularity: 9,
    fields: [
      { id: 'email', label: 'Email or Phone', placeholder: 'jane@example.com', format: 'email', position: 'front', required: true, maxLength: 50 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'bank', label: 'Bank', placeholder: 'Chase', format: 'freeform', position: 'front', required: false, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#6D1ED4' },
  },
  {
    id: 'interac_etransfer',
    name: 'Interac e-Transfer',
    shortName: 'e-Transfer',
    category: 'realtime_payment',
    region: 'north_america',
    country: 'CA',
    logoFile: '/logos/rails/rtp/interac-etransfer.svg',
    popularity: 9,
    fields: [
      { id: 'email', label: 'Email or Phone', placeholder: 'jane@example.com', format: 'email', position: 'front', required: true, maxLength: 50 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'autodeposit', label: 'Autodeposit', placeholder: 'Enabled', format: 'freeform', position: 'front', required: false, maxLength: 10 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#FFB800', secondary: '#F7941D' },
  },
  {
    id: 'paynow',
    name: 'PayNow',
    category: 'realtime_payment',
    region: 'asia_pacific',
    country: 'SG',
    logoFile: '/logos/rails/rtp/paynow.svg',
    popularity: 7,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#FF0000' },
  },
  {
    id: 'promptpay',
    name: 'PromptPay',
    category: 'realtime_payment',
    region: 'asia_pacific',
    country: 'TH',
    logoFile: '/logos/rails/rtp/promptpay.svg',
    popularity: 7,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#1A3668' },
  },
  {
    id: 'duitnow',
    name: 'DuitNow',
    category: 'realtime_payment',
    region: 'asia_pacific',
    country: 'MY',
    logoFile: '/logos/rails/rtp/duitnow.svg',
    popularity: 6,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#E4002B' },
  },
  {
    id: 'swish',
    name: 'Swish',
    category: 'realtime_payment',
    region: 'europe',
    country: 'SE',
    logoFile: '/logos/rails/rtp/swish.svg',
    popularity: 7,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#F2A81D' },
  },
  {
    id: 'vipps',
    name: 'Vipps',
    category: 'realtime_payment',
    region: 'europe',
    country: 'NO',
    logoFile: '/logos/rails/rtp/vipps.svg',
    popularity: 6,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#FF5B24' },
  },
  {
    id: 'mobilepay',
    name: 'MobilePay',
    category: 'realtime_payment',
    region: 'europe',
    country: 'DK',
    logoFile: '/logos/rails/rtp/mobilepay.svg',
    popularity: 6,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#5A78FF' },
  },
  {
    id: 'npp',
    name: 'New Payments Platform',
    shortName: 'NPP / Osko',
    category: 'realtime_payment',
    region: 'asia_pacific',
    country: 'AU',
    logoFile: '/logos/rails/rtp/npp.svg',
    popularity: 7,
    fields: [
      { id: 'payid', label: 'PayID', placeholder: 'jane@example.com', format: 'email', position: 'front', required: true, maxLength: 50 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'bank', label: 'Bank', placeholder: 'Commonwealth Bank', format: 'freeform', position: 'front', required: false, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#00A9CE' },
  },
  {
    id: 'spei',
    name: 'SPEI',
    category: 'realtime_payment',
    region: 'latin_america',
    country: 'MX',
    logoFile: '/logos/rails/rtp/spei.svg',
    popularity: 7,
    fields: [
      { id: 'clabe', label: 'CLABE', placeholder: '012345678901234567', format: 'freeform', position: 'front', required: true, maxLength: 18 },
      { id: 'holder', label: 'Beneficiary', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'bank', label: 'Bank', placeholder: 'BBVA México', format: 'freeform', position: 'front', required: false, maxLength: 35 },
      { id: 'reference', label: 'Reference', placeholder: '1234567', format: 'freeform', position: 'front', required: false, maxLength: 7 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#004E2C' },
  },
  {
    id: 'tips',
    name: 'TIPS',
    shortName: 'TIPS (ECB)',
    category: 'realtime_payment',
    region: 'europe',
    countries: ['EU'],
    logoFile: '/logos/rails/rtp/tips.svg',
    popularity: 5,
    fields: sepaFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003399' },
  },

  // ═══════════════════════════════════════════════════════════
  // WIRE / RTGS
  // ═══════════════════════════════════════════════════════════

  {
    id: 'swift',
    name: 'SWIFT',
    shortName: 'SWIFT gpi',
    category: 'wire_rtgs',
    region: 'global',
    logoFile: '/logos/rails/wire/swift.svg',
    popularity: 10,
    fields: wireFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#005EB8' },
  },
  {
    id: 'fedwire',
    name: 'Fedwire',
    category: 'wire_rtgs',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/wire/fedwire.svg',
    popularity: 9,
    fields: [
      { id: 'routing', label: 'ABA Routing', placeholder: '021000021', format: 'routing_number', position: 'front', required: true, maxLength: 9 },
      { id: 'account', label: 'Account Number', placeholder: '123456789012', format: 'freeform', position: 'front', required: true, maxLength: 17 },
      { id: 'beneficiary', label: 'Beneficiary', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'bank', label: 'Receiving Bank', placeholder: 'JPMorgan Chase', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'reference', label: 'Reference', placeholder: 'Wire ref', format: 'freeform', position: 'front', required: false, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003A70' },
  },
  {
    id: 'chips',
    name: 'CHIPS',
    category: 'wire_rtgs',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/wire/chips.svg',
    popularity: 7,
    fields: wireFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#1B365D' },
  },
  {
    id: 'chaps',
    name: 'CHAPS',
    category: 'wire_rtgs',
    region: 'europe',
    country: 'GB',
    logoFile: '/logos/rails/wire/chaps.svg',
    popularity: 8,
    fields: [
      ...ukBankFields,
      { id: 'bic', label: 'BIC', placeholder: 'BARCGB22XXX', format: 'swift_bic', position: 'front', required: false, maxLength: 11 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#1D1D1B' },
  },
  {
    id: 'target2',
    name: 'TARGET2',
    shortName: 'T2',
    category: 'wire_rtgs',
    region: 'europe',
    countries: ['EU'],
    logoFile: '/logos/rails/wire/target2.svg',
    popularity: 7,
    fields: sepaFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003399' },
  },
  {
    id: 'lynx',
    name: 'Lynx',
    shortName: 'Lynx (CA)',
    category: 'wire_rtgs',
    region: 'north_america',
    country: 'CA',
    logoFile: '/logos/rails/wire/lynx.svg',
    popularity: 6,
    fields: [
      { id: 'transit', label: 'Transit + Institution', placeholder: '00001-001', format: 'freeform', position: 'front', required: true, maxLength: 12 },
      { id: 'account', label: 'Account Number', placeholder: '1234567', format: 'freeform', position: 'front', required: true, maxLength: 12 },
      { id: 'beneficiary', label: 'Beneficiary', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
      { id: 'bank', label: 'Bank', placeholder: 'Royal Bank of Canada', format: 'freeform', position: 'front', required: false, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003366' },
  },
  {
    id: 'bojnet',
    name: 'BOJ-NET',
    category: 'wire_rtgs',
    region: 'asia_pacific',
    country: 'JP',
    logoFile: '/logos/rails/wire/bojnet.svg',
    popularity: 5,
    fields: wireFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#8B0000' },
  },
  {
    id: 'cips',
    name: 'CIPS',
    shortName: 'CIPS (CN)',
    category: 'wire_rtgs',
    region: 'asia_pacific',
    country: 'CN',
    logoFile: '/logos/rails/wire/cips.svg',
    popularity: 6,
    fields: wireFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#DE2910' },
  },
  {
    id: 'sic',
    name: 'SIC / euroSIC',
    shortName: 'SIC',
    category: 'wire_rtgs',
    region: 'europe',
    country: 'CH',
    logoFile: '/logos/rails/wire/sic.svg',
    popularity: 5,
    fields: [
      { id: 'iban', label: 'IBAN', placeholder: 'CH93 0076 2011 6238 5295 7', format: 'iban', position: 'front', required: true, maxLength: 34 },
      { id: 'bic', label: 'BIC', placeholder: 'UBSWCHZH80A', format: 'swift_bic', position: 'front', required: true, maxLength: 11 },
      { id: 'beneficiary', label: 'Beneficiary', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#D52B1E' },
  },

  // ═══════════════════════════════════════════════════════════
  // ACH / BATCH
  // ═══════════════════════════════════════════════════════════

  {
    id: 'ach',
    name: 'ACH',
    shortName: 'ACH (Nacha)',
    category: 'ach_batch',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/ach/nacha.svg',
    popularity: 10,
    fields: achFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003A70' },
  },
  {
    id: 'bacs',
    name: 'Bacs',
    category: 'ach_batch',
    region: 'europe',
    country: 'GB',
    logoFile: '/logos/rails/ach/bacs.svg',
    popularity: 8,
    fields: ukBankFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#00A3E0' },
  },
  {
    id: 'sepa_dd',
    name: 'SEPA Direct Debit',
    shortName: 'SEPA DD',
    category: 'ach_batch',
    region: 'europe',
    countries: ['EU'],
    logoFile: '/logos/rails/ach/sepa.svg',
    popularity: 9,
    fields: [
      ...sepaFields,
      { id: 'creditor_id', label: 'Creditor ID', placeholder: 'DE98ZZZ09999999999', format: 'freeform', position: 'front', required: false, maxLength: 35 },
      { id: 'mandate', label: 'Mandate Reference', placeholder: 'MNDT-2024-001', format: 'freeform', position: 'front', required: false, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003399' },
  },
  {
    id: 'sepa_ct',
    name: 'SEPA Credit Transfer',
    shortName: 'SEPA CT',
    category: 'ach_batch',
    region: 'europe',
    countries: ['EU'],
    logoFile: '/logos/rails/ach/sepa.svg',
    popularity: 9,
    fields: sepaFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003399' },
  },
  {
    id: 'eft_ca',
    name: 'EFT',
    shortName: 'EFT (Canada)',
    category: 'ach_batch',
    region: 'north_america',
    country: 'CA',
    logoFile: '/logos/rails/ach/eft-ca.svg',
    popularity: 7,
    fields: [
      { id: 'transit', label: 'Transit Number', placeholder: '00001', format: 'freeform', position: 'front', required: true, maxLength: 5 },
      { id: 'institution', label: 'Institution Number', placeholder: '001', format: 'freeform', position: 'front', required: true, maxLength: 3 },
      { id: 'account', label: 'Account Number', placeholder: '1234567', format: 'freeform', position: 'front', required: true, maxLength: 12 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003366' },
  },
  {
    id: 'becs',
    name: 'BECS',
    shortName: 'BECS (AU)',
    category: 'ach_batch',
    region: 'asia_pacific',
    country: 'AU',
    logoFile: '/logos/rails/ach/becs.svg',
    popularity: 6,
    fields: [
      { id: 'bsb', label: 'BSB', placeholder: '062-000', format: 'freeform', position: 'front', required: true, maxLength: 7 },
      { id: 'account', label: 'Account Number', placeholder: '12345678', format: 'freeform', position: 'front', required: true, maxLength: 9 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#002B5C' },
  },
  {
    id: 'zengin',
    name: 'Zengin',
    category: 'ach_batch',
    region: 'asia_pacific',
    country: 'JP',
    logoFile: '/logos/rails/ach/zengin.svg',
    popularity: 6,
    fields: [
      { id: 'bank_code', label: 'Bank Code', placeholder: '0001', format: 'freeform', position: 'front', required: true, maxLength: 4 },
      { id: 'branch_code', label: 'Branch Code', placeholder: '001', format: 'freeform', position: 'front', required: true, maxLength: 3 },
      { id: 'account', label: 'Account Number', placeholder: '1234567', format: 'freeform', position: 'front', required: true, maxLength: 7 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Tanaka Taro', format: 'freeform', position: 'front', required: true, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#8B0000' },
  },
  {
    id: 'nach',
    name: 'NACH',
    shortName: 'NACH (India)',
    category: 'ach_batch',
    region: 'asia_pacific',
    country: 'IN',
    logoFile: '/logos/rails/ach/nach.svg',
    popularity: 6,
    fields: [
      { id: 'ifsc', label: 'IFSC Code', placeholder: 'SBIN0001234', format: 'freeform', position: 'front', required: true, maxLength: 11 },
      { id: 'account', label: 'Account Number', placeholder: '12345678901', format: 'freeform', position: 'front', required: true, maxLength: 18 },
      { id: 'holder', label: 'Account Holder', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#FF6600' },
  },

  // ═══════════════════════════════════════════════════════════
  // MOBILE MONEY
  // ═══════════════════════════════════════════════════════════

  {
    id: 'mpesa',
    name: 'M-Pesa',
    category: 'mobile_money',
    region: 'africa',
    countries: ['KE', 'TZ', 'GH', 'MZ', 'ET'],
    logoFile: '/logos/rails/mobile/mpesa.svg',
    popularity: 10,
    fields: mobileMoneyFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#4CAF50', secondary: '#2E7D32' },
  },
  {
    id: 'mtn_momo',
    name: 'MTN MoMo',
    shortName: 'MTN MoMo',
    category: 'mobile_money',
    region: 'africa',
    countries: ['GH', 'UG', 'CI', 'CM', 'ZA'],
    logoFile: '/logos/rails/mobile/mtn.svg',
    popularity: 9,
    fields: mobileMoneyFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#FFCC00', secondary: '#000000' },
  },
  {
    id: 'airtel_money',
    name: 'Airtel Money',
    category: 'mobile_money',
    region: 'africa',
    countries: ['UG', 'KE', 'TZ', 'MW', 'RW'],
    logoFile: '/logos/rails/mobile/airtel.svg',
    popularity: 7,
    fields: mobileMoneyFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#ED1C24' },
  },
  {
    id: 'gcash',
    name: 'GCash',
    category: 'mobile_money',
    region: 'asia_pacific',
    country: 'PH',
    logoFile: '/logos/rails/mobile/gcash.svg',
    popularity: 8,
    fields: [
      { id: 'phone', label: 'Mobile Number', placeholder: '+63 917 123 4567', format: 'phone', position: 'front', required: true, maxLength: 15 },
      { id: 'holder', label: 'Account Name', placeholder: 'Jane Doe', format: 'freeform', position: 'front', required: true, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#007DFE' },
  },
  {
    id: 'gopay',
    name: 'GoPay',
    category: 'mobile_money',
    region: 'asia_pacific',
    country: 'ID',
    logoFile: '/logos/rails/mobile/gopay.svg',
    popularity: 7,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#00AA13' },
  },
  {
    id: 'ovo',
    name: 'OVO',
    category: 'mobile_money',
    region: 'asia_pacific',
    country: 'ID',
    logoFile: '/logos/rails/mobile/ovo.svg',
    popularity: 7,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#4C3494' },
  },
  {
    id: 'dana',
    name: 'DANA',
    category: 'mobile_money',
    region: 'asia_pacific',
    country: 'ID',
    logoFile: '/logos/rails/mobile/dana.svg',
    popularity: 6,
    fields: rtpPhoneFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#108EE9' },
  },
  {
    id: 'wave',
    name: 'Wave',
    category: 'mobile_money',
    region: 'africa',
    countries: ['SN', 'CI', 'ML', 'BF', 'UG'],
    logoFile: '/logos/rails/mobile/wave.svg',
    popularity: 7,
    fields: mobileMoneyFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#1B82E0' },
  },
  {
    id: 'orange_money',
    name: 'Orange Money',
    category: 'mobile_money',
    region: 'africa',
    countries: ['SN', 'CI', 'ML', 'CM', 'MG'],
    logoFile: '/logos/rails/mobile/orange.svg',
    popularity: 7,
    fields: mobileMoneyFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'mobile_first',
    defaultColors: { primary: '#FF6600' },
  },

  // ═══════════════════════════════════════════════════════════
  // BNPL
  // ═══════════════════════════════════════════════════════════

  {
    id: 'klarna',
    name: 'Klarna',
    category: 'bnpl',
    region: 'global',
    country: 'SE',
    logoFile: '/logos/rails/bnpl/klarna.svg',
    popularity: 10,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#FFB3C7', secondary: '#0A0B09' },
  },
  {
    id: 'afterpay',
    name: 'Afterpay',
    shortName: 'Afterpay / Clearpay',
    category: 'bnpl',
    region: 'global',
    country: 'AU',
    logoFile: '/logos/rails/bnpl/afterpay.svg',
    popularity: 9,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#B2FCE4', secondary: '#000000' },
  },
  {
    id: 'affirm',
    name: 'Affirm',
    category: 'bnpl',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/bnpl/affirm.svg',
    popularity: 9,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#4A4AF4' },
  },
  {
    id: 'zip',
    name: 'Zip',
    shortName: 'Zip (QuadPay)',
    category: 'bnpl',
    region: 'global',
    country: 'AU',
    logoFile: '/logos/rails/bnpl/zip.svg',
    popularity: 7,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#AA8FFF' },
  },
  {
    id: 'tabby',
    name: 'Tabby',
    category: 'bnpl',
    region: 'middle_east',
    country: 'AE',
    logoFile: '/logos/rails/bnpl/tabby.svg',
    popularity: 7,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#3BFFC0' },
  },
  {
    id: 'tamara',
    name: 'Tamara',
    category: 'bnpl',
    region: 'middle_east',
    country: 'SA',
    logoFile: '/logos/rails/bnpl/tamara.svg',
    popularity: 6,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#F5D100' },
  },
  {
    id: 'atome',
    name: 'Atome',
    category: 'bnpl',
    region: 'asia_pacific',
    country: 'SG',
    logoFile: '/logos/rails/bnpl/atome.svg',
    popularity: 5,
    fields: bnplFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#FF6B6B' },
  },

  // ═══════════════════════════════════════════════════════════
  // CRYPTO / DIGITAL ASSETS
  // ═══════════════════════════════════════════════════════════

  {
    id: 'bitcoin_ln',
    name: 'Bitcoin Lightning',
    shortName: 'BTC Lightning',
    category: 'crypto',
    region: 'global',
    logoFile: '/logos/rails/crypto/bitcoin.svg',
    popularity: 10,
    fields: [
      { id: 'address', label: 'Lightning Address', placeholder: 'jane@wallet.com', format: 'email', position: 'front', required: true, maxLength: 64 },
      { id: 'chain', label: 'Network', placeholder: 'Lightning Network', format: 'freeform', position: 'front', required: false, maxLength: 25 },
      { id: 'holder', label: 'Display Name', placeholder: 'jane', format: 'freeform', position: 'front', required: false, maxLength: 35 },
    ],
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#F7931A' },
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    shortName: 'ETH',
    category: 'crypto',
    region: 'global',
    logoFile: '/logos/rails/crypto/ethereum.svg',
    popularity: 9,
    fields: cryptoFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#627EEA' },
  },
  {
    id: 'stellar',
    name: 'Stellar',
    shortName: 'XLM',
    category: 'crypto',
    region: 'global',
    logoFile: '/logos/rails/crypto/stellar.svg',
    popularity: 7,
    fields: cryptoFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#000000' },
  },
  {
    id: 'ripple',
    name: 'Ripple',
    shortName: 'XRP',
    category: 'crypto',
    region: 'global',
    logoFile: '/logos/rails/crypto/ripple.svg',
    popularity: 7,
    fields: cryptoFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#0085C0' },
  },
  {
    id: 'solana_pay',
    name: 'Solana Pay',
    shortName: 'SOL',
    category: 'crypto',
    region: 'global',
    logoFile: '/logos/rails/crypto/solana.svg',
    popularity: 7,
    fields: cryptoFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#9945FF', secondary: '#14F195' },
  },
  {
    id: 'usdc',
    name: 'USDC',
    shortName: 'USDC (Circle)',
    category: 'crypto',
    region: 'global',
    logoFile: '/logos/rails/crypto/usdc.svg',
    popularity: 8,
    fields: cryptoFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: true,
    cardFormFactor: 'virtual_only',
    defaultColors: { primary: '#2775CA' },
  },

  // ═══════════════════════════════════════════════════════════
  // OPEN BANKING / A2A
  // ═══════════════════════════════════════════════════════════

  {
    id: 'openbanking_uk',
    name: 'Open Banking',
    shortName: 'OB (UK)',
    category: 'open_banking',
    region: 'europe',
    country: 'GB',
    logoFile: '/logos/rails/openbanking/ob-uk.svg',
    popularity: 8,
    fields: openBankingFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#2B2D42' },
  },
  {
    id: 'psd2',
    name: 'PSD2',
    shortName: 'PSD2 (EU)',
    category: 'open_banking',
    region: 'europe',
    countries: ['EU'],
    logoFile: '/logos/rails/openbanking/psd2.svg',
    popularity: 7,
    fields: openBankingFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#003399' },
  },
  {
    id: 'plaid',
    name: 'Plaid',
    category: 'open_banking',
    region: 'north_america',
    country: 'US',
    logoFile: '/logos/rails/openbanking/plaid.svg',
    popularity: 8,
    fields: openBankingFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#000000' },
  },
  {
    id: 'truelayer',
    name: 'TrueLayer',
    category: 'open_banking',
    region: 'europe',
    country: 'GB',
    logoFile: '/logos/rails/openbanking/truelayer.svg',
    popularity: 6,
    fields: openBankingFields,
    hasChip: false,
    hasContactless: false,
    hasQrCode: false,
    cardFormFactor: 'document',
    defaultColors: { primary: '#0050FF' },
  },
];

// Quick lookup map
export const railsById = new Map(paymentRails.map(r => [r.id, r]));
